//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKyLTHDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.ThanNhans = new HashSet<ThanNhan>();
        }
    
        public string Masv { get; set; }
        public string TenSV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string Lop { get; set; }
        public string GioiTinh { get; set; }
        public System.DateTime NgayVaoO { get; set; }
        public string SDT { get; set; }
        public string email { get; set; }
        public string MK { get; set; }
        public Nullable<int> MaPhg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanNhan> ThanNhans { get; set; }
    }
}
