//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKyLTHDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanNhan
    {
        public int MaTN { get; set; }
        public string Masv { get; set; }
        public string TenTN { get; set; }
        public string QuanHe { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
